### PR TITLE
Modules/Parsers/Maps Overhaul

### PR DESCRIPTION
**Pull request by AustinLMayes**
Adds Map, a file to represent a loaded map (worlds not done yet)
Adds MapManager, just a simple container of all of the loaded maps.
Makes it so parsers are registered at application launch and are now parsed on map load, not match load.
Sandboxes modules into a manager instance that is managed by a Map instance.
Makes it so Maps are the files that handle parsing and that yml is parsed on launch.
Matches only live as long as they are being played and have nothing to do with parsing
Breaks a ton of code that relies on the old system. You should look into that @KyloCode
Adds an annotation to help in the organization of parsers.
Adds dependencies to parsers.
Does some other stuff that I probably left out :)

### CODE REVIEW

**Comment by dentmaged** [comment]
@AustinLMayes You may not want to make the module a class, but rather an interface as a class can have only one superclass, and some modules may extend other things.

**Comment by AustinLMayes** [comment]
@dentmaged I did this so some modules don't need the destroy() method and I didn't wan empty overrides in a lot of places.

**Comment by AustinLMayes** [comment]
@dentmaged nevermind, I did it anyway.

**Comment by AustinLMayes** [comment]
@KyloCode This is good to be merged, all loading and parsing works.
\cc @steven5703 @Tanpiku @UmbreonMessiah

**Comment by ViceWatercolour** [comment]
@AustinLMayes I don't have write access to this repo, but I'll pass this on for you

**Comment by thekeenant** [comment]
So what's the role of modules if parsers contain the same data?

Originally, parsers were intended to be the method of creating the modules which hold all the information necessary since that is used during the match, and sometimes beforehand (ex. MapModule - later it would be designated which are loaded prior to the match). It separated the often complex parsing from what goes on during the match.

**Comment by AustinLMayes** [comment]
@KyloCode Parsers parse and also hold the data associated with the map. Modules are for things such as listeners and things that only need to be active during a match. Parsers are attached to maps, and store all the data needed to play a map. Modules just put the data to use when the map is running, and go away when the match ends. Parsers never go away.

**Comment by dentmaged** [comment]
@KyloCode @AustinLMayes May I say what I would do?

**EDIT: Date: 26/07/15:** @swivr

**Comment by thekeenant** [comment]
@AustinLMayes I guess I just find it weird that (a) the parser classes contain the parsed data and (b) that it's done through static methods via reflection. Just seems like unnecessary complication.

@dentmaged Of course.

**Comment by AustinLMayes** [comment]
@KyloCode the only reason I used reflection is for the rare chance that a parser would not need to create a module. They are static methods so unnecessary instances of parsers that aren't used don't need to be created. 

In theory, we could separate parsers -> modules -> matchinstancemodules but that seems complicated as well.

**Comment by dentmaged** [comment]
@KyloCode @AustinLMayes Thanks! I don't want to be rude and intrude on your conversation! The parser returns a module or null, if the module is disabled, the module implements listener. The module has a list/map, which on an event, the module loops through all instances of the data class (for `TeamsModule`, it would be `Team` - I don't know what to call the `Team` class), you can see it in my email I sent to you. Once looped through each module, it will do a check like if the wool should be placed there or the block mined is the monument block.

Here's how I'd like my module system to work (if I were to make one): There is one parser instance. Match.init() -> ModuleParser returns a module or null -> If not null -> Register module -> Add to module map.

**Comment by AustinLMayes** [comment]
@dentmaged This is a public repo, you can provide as much feedback as you want. :)

Some suggestions:
1. Modules are parsed on match load, this will drastically slow down loading times.
2. I like that module will implement listener, but I think all checking should be done in the module, without a list of other things to check. Put most logic in module.

Also, a thought for @KyloCode to ponder: Maybe we could add a way to also register commands on module creation, for match-specific commands.

**Comment by dentmaged** [comment]
@AustinLMayes Thanks!

I'd just like to address your points:
1. Modules and parser instances are created on match load and I believe that the servers are extremely fast at cycling/loading maps. Just a note: I use Apache's Commons IO to copy the directory.
2. I haven't seen too much lag with my current system unless if you cap two wools within a few seconds.

And, for my version of Icarus, I used sk89q's command framework, which can be found [here](https://github.com/OvercastNetwork/sk89q-command-framework).

**Comment by AustinLMayes** [comment]
@dentmaged A few things:

Intake is better, you can see an implementation of it in Bukkit in my Commons repo.

Imagine if there were a 100 modules to parse, that would drastically slow down match loading, it's best to get the heavy lifting out of the way before players begin interaction with the server.

Seeing lag when you cap 2 wools within a few seconds is enough to cause concern. Imagine f you had many teams completing different objectives within a short amount of time. Also, I would assume control points would be extremely costly in your system

Also, copying directories would be done a match init, just not parsing (would have to fresh copy each time.)

**Comment by AustinLMayes** [comment]
Is this going to be merged? ever?

**Comment by ViceWatercolour** [comment]
@AustinLMayes I believe Keenan is on leave right now.

**Comment by thekeenant** [comment]
I'm not sure, not convinced this is a better way to go. I really think think the current object oriented approach is fine, and more standard (factory classes).

**Comment by AustinLMayes** [comment]
@swivr but the way it goes now, stuff is parsed on match load, and there is no Map class. I'm sure that combining both strategies and just reworking parsers a bit could be a better solution.

**Comment by thekeenant** [comment]
Hmm, well currently modules would be parsed before match load, right on server start if they are in the rotation. A class that handles the map loading and downloading will be needed.

**Comment by AustinLMayes** [comment]
@swivr I think all maps (even not in rotation) should be loaded.

**Comment by AustinLMayes** [comment]
Also, I think parsing should be separate from match instance. Map != Match

**Comment by thekeenant** [comment]
They could be loaded out of the rotation as well, it's loaded whenever it's called. Match is actually more of a Map instance, but that's a separate issue and something to discuss.

**Comment by AustinLMayes** [comment]
@swivr I still think the gist of what I've done (Parsing stuff registered on plugin load, map loads create new instance) so that stuff can be contained in a manager and can be easily referenced. I don't think everything should be stuffed into a Map class.

**Comment by dentmaged** [comment]
@AustinLMayes I agree with all maps in the repository being loaded so then staff can type `/sn <map name>`. I think that the rotation manager should load all maps in the `maps` folder in the server root and add them to an array list/hashmap (if a hashmap, add their name).

The plugin on enable, creates the RotationManager and loads all the maps. The server then cycles to the next map. match.init() is called (all modules are then parsed) and a cycle complete event is called.

@swivr I think matches should be a separate class to maps, but I think matches should have a map variable.

**Comment by AustinLMayes** [comment]
@dentmaged Your concept of how the plugin should start and load maps almost sounds identical to how Overcast's PGM handles loading. Seeing as you have had previous DMCA notices from the Overcast Team, I think it would be wise for you to not replicate their code in a public repository as well. Trust me, it isn't worth it.

**Comment by dentmaged** [comment]
@AustinLMayes most of that is from working on CardinalPGM and my own plugins. That's how I did it on my server and it seems to work fine. Oh yeah, the lag between two wools being capped is because of my server with barely any RAM.

**Comment by AustinLMayes** [comment]
@dentmaged This is no place for a PGM clone.

**Comment by ViceWatercolour** [comment]
Try not to get hostile!

I think the point was made by ALM. And, if it's recycled code that is too similar to something that'd get us DMCA'd, it's probably wise to not use it.

**Comment by dentmaged** [comment]
@AustinLMayes Sorry, I've been on holiday. I never said that this is a place for a PGM clone, but how would you recommend how to load maps and start the plugin?

**Comment by AustinLMayes** [comment]
Welp, seing as this has ben inactive for about a month... @keenanthompson can reopen if he wishes.

**Pull request closed without merging**
